version: "3"
services:
  jenkins:
    image: 'jenkins/jenkins:lts-alpine-jdk11'
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
    driver: local
